"""Адаптер Claude Code: канон -> .claude/agents/<name>.md

Схема сабагента (документация Claude Code, «Subagents / Supported frontmatter
fields»): обязательны `name` и `description`; из необязательных мы используем
`tools`, `model` и `effort`.

Наблюдения этапа 5, реализованные здесь (docs/harness-differences.md):

1. Границы доступа задаются СПИСКОМ ИНСТРУМЕНТОВ, а не песочницей. Поэтому
   `shell` без `filesystem-write` невыразим: Bash немедленно возвращает запись
   через `sed -i`. Генерация падает — см. Inexpressible.

2. `effort` носитель ИМЕЕТ: одноимённое поле frontmatter, перекрывающее effort
   сессии. Раньше адаптер утверждал обратное и выбрасывал значение с предупреждением,
   из-за чего заданное в каноне усилие подменялось наследованием настроек сессии.
   Расхождение осей между харнессами тут не в наличии носителя, а в наборе значений
   и в том, что у Claude доступность уровня зависит от модели.
"""
from pathlib import Path

from . import Inexpressible, RenderError

TARGET_DIR = ".claude/agents"
EXT = ".md"

# Одна capability -> инструменты, которые её обеспечивают.
CAP_TOOLS = {
    "filesystem-read":  ["Read"],
    "code-search":      ["Grep", "Glob"],
    "filesystem-write": ["Edit", "Write"],
    "shell":            ["Bash"],
    "vcs":              ["Bash"],
    "web":              ["WebFetch", "WebSearch"],
}

# Инструменты, дающие запись в ФС как побочный эффект.
WRITE_GRANTING = {"Bash", "Edit", "Write"}

TOOL_ORDER = ["Read", "Grep", "Glob", "Edit", "Write", "Bash", "WebFetch", "WebSearch"]

# Уровни effort у Claude Code (docs/en/model-config, «Adjust effort level») и их
# поддержка моделями. Канон знает только low/medium/high — пересечение, доступное
# везде; xhigh/max перечислены, чтобы таблица описывала ось целиком, а не наш срез.
#
# Проверять совместимость обязательно ЗДЕСЬ: при неподдерживаемом уровне харнесс
# молча понижает его до ближайшего поддерживаемого сверху вниз. Тихое понижение —
# ровно тот исход, ради исключения которого генератор и написан: определение
# утверждало бы усилие, которого на самом деле нет.
#
# VERIFY: таблица написана по документации и не проверялась запуском. Модели, которых
# в ней нет, не считаются несовместимыми — они считаются НЕИЗВЕСТНЫМИ (предупреждение).
EFFORT_LEVELS = ["low", "medium", "high", "xhigh", "max"]
FULL_RANGE = set(EFFORT_LEVELS)
MODEL_EFFORT = {
    "opus":   FULL_RANGE,
    "sonnet": FULL_RANGE,
    "fable":  FULL_RANGE,
}

MARKER = "GENERATED by tools/gen_agents.py"


def render(agent, source_dir=".agents/agents"):
    caps = set(agent["capabilities"])
    warnings = []

    tools = set()
    for c in caps:
        tools.update(CAP_TOOLS[c])

    # --- проверка выразимости границы -------------------------------------
    if "filesystem-write" not in caps:
        leaks = sorted(tools & WRITE_GRANTING)
        if leaks:
            via = ", ".join(sorted(c for c in caps if set(CAP_TOOLS[c]) & WRITE_GRANTING))
            raise Inexpressible(
                f"агент '{agent['name']}': запрет записи невыразим в Claude Code.\n"
                f"    capabilities не содержат 'filesystem-write', но '{via}' требует "
                f"{', '.join(leaks)},\n"
                f"    а через него запись возвращается (например `sed -i`).\n"
                f"    У Claude границу задаёт список инструментов, а не песочница, "
                f"поэтому read-only + shell выразить нечем.\n"
                f"    Варианты: убрать '{via}' из capabilities, либо добавить "
                f"'filesystem-write' и признать, что агент пишет."
            )

    effort = (agent.get("effort") or "").strip()
    model = agent["models"]["claude"]
    warnings.extend(_check_effort(agent["name"], effort, model))

    ordered = [t for t in TOOL_ORDER if t in tools]
    src = f"{Path(source_dir).as_posix()}/{agent['name']}.md"

    text = (
        "---\n"
        f"name: {agent['name']}\n"
        "description: >\n"
        + "".join(f"  {ln}\n" for ln in _wrap(agent["description"]))
        + f"tools: {', '.join(ordered)}\n"
        f"model: {model}\n"
        + (f"effort: {effort}\n" if effort else "")
        + "---\n\n"
        f"<!-- {MARKER} from {src} — do not edit -->\n\n"
        f"{agent['body'].strip()}\n"
    )
    return text, warnings


def _check_effort(name, effort, model):
    """Совместимость уровня усилия с моделью. Возвращает предупреждения."""
    if not effort:
        return []

    if effort not in FULL_RANGE:
        raise RenderError(
            f"агент '{name}': effort='{effort}' не является уровнем Claude Code "
            f"({', '.join(EFFORT_LEVELS)})"
        )

    supported = MODEL_EFFORT.get(model)
    if supported is None:
        return [
            f"агент '{name}': модель '{model}' не описана в таблице уровней effort — "
            f"effort='{effort}' перенесён как есть, совместимость не проверена "
            f"(VERIFY, adapters/claude.py)"
        ]

    if effort not in supported:
        raise RenderError(
            f"агент '{name}': модель '{model}' не поддерживает effort='{effort}' "
            f"(поддерживается: {', '.join(l for l in EFFORT_LEVELS if l in supported)}).\n"
            f"    Харнесс понизил бы уровень молча, и определение утверждало бы усилие, "
            f"которого нет.\n"
            f"    Варианты: понизить effort в каноне либо выбрать модель, "
            f"поддерживающую этот уровень."
        )

    return []


def _wrap(text, width=88):
    words, line, out = text.split(), "", []
    for w in words:
        if line and len(line) + 1 + len(w) > width:
            out.append(line)
            line = w
        else:
            line = f"{line} {w}".strip()
    if line:
        out.append(line)
    return out
