"""Claude Code adapter: canonical definitions -> .claude/agents/<name>.md

Subagent schema (Claude Code documentation, "Subagents / Supported frontmatter
fields"): `name` and `description` are required; we also use the optional
`tools`, `model`, and `effort` fields.

Phase 5 observations implemented here (docs/harness-differences.md):

1. Access boundaries use a TOOL LIST rather than a sandbox. Thus `shell` without
   `filesystem-write` cannot be expressed: Bash immediately restores write access
   through `sed -i`. Generation fails; see Inexpressible.

2. `effort` DOES have a native field: the frontmatter field of the same name
   overrides session effort. The adapter previously claimed otherwise and dropped
   the value with a warning, replacing canonical effort with inherited session
   settings. The harnesses differ in accepted values and Claude's model-dependent
   availability of effort levels, not in whether such a field exists.
"""
from pathlib import Path

from . import Inexpressible, RenderError

TARGET_DIR = ".claude/agents"
EXT = ".md"

# One capability -> the tools that provide it.
CAP_TOOLS = {
    "filesystem-read":  ["Read"],
    "code-search":      ["Grep", "Glob"],
    "filesystem-write": ["Edit", "Write"],
    "shell":            ["Bash"],
    "vcs":              ["Bash"],
    "web":              ["WebFetch", "WebSearch"],
}

# Tools that grant filesystem write access as a side effect.
WRITE_GRANTING = {"Bash", "Edit", "Write"}

TOOL_ORDER = ["Read", "Grep", "Glob", "Edit", "Write", "Bash", "WebFetch", "WebSearch"]

# Claude Code effort levels (docs/en/model-config, "Adjust effort level") and
# model support. Canonical definitions only use low/medium/high, the shared subset;
# xhigh/max are listed so the table describes the full range, not just our subset.
#
# Compatibility MUST be checked HERE: the harness silently lowers an unsupported
# effort level to the nearest supported level below it. Preventing that silent
# downgrade is exactly why this generator exists: the definition would otherwise
# claim an effort level that is not actually applied.
#
# VERIFY: this table comes from documentation and has not been tested at runtime.
# Unlisted models are UNKNOWN (warning), rather than assumed incompatible.
EFFORT_LEVELS = ["low", "medium", "high", "xhigh", "max"]
FULL_RANGE = set(EFFORT_LEVELS)
MODEL_EFFORT = {
    "opus":   FULL_RANGE,
    "sonnet": FULL_RANGE,
    "fable":  FULL_RANGE,
}

MARKER = "GENERATED by tools/gen_agents.py"


def render(agent, source_dir=".agents/agents"):
    caps = set(agent["capabilities"])
    warnings = []

    tools = set()
    for c in caps:
        tools.update(CAP_TOOLS[c])

    # --- check whether the boundary can be expressed -------------------------------------
    if "filesystem-write" not in caps:
        leaks = sorted(tools & WRITE_GRANTING)
        if leaks:
            via = ", ".join(sorted(c for c in caps if set(CAP_TOOLS[c]) & WRITE_GRANTING))
            raise Inexpressible(
                f"agent '{agent['name']}': Claude Code cannot express the write prohibition.\n"
                f"    capabilities do not include 'filesystem-write', but '{via}' requires "
                f"{', '.join(leaks)},\n"
                f"    which restores write access (for example, `sed -i`).\n"
                f"    Claude uses a tool list, not a sandbox, to define the boundary, "
                f"so read-only + shell cannot be expressed.\n"
                f"    Options: remove '{via}' from capabilities, or add "
                f"'filesystem-write' and acknowledge that the agent can write."
            )

    effort = (agent.get("effort") or "").strip()
    model = agent["models"]["claude"]
    warnings.extend(_check_effort(agent["name"], effort, model))

    ordered = [t for t in TOOL_ORDER if t in tools]
    src = f"{Path(source_dir).as_posix()}/{agent['name']}.md"

    text = (
        "---\n"
        f"name: {agent['name']}\n"
        "description: >\n"
        + "".join(f"  {ln}\n" for ln in _wrap(agent["description"]))
        + f"tools: {', '.join(ordered)}\n"
        f"model: {model}\n"
        + (f"effort: {effort}\n" if effort else "")
        + "---\n\n"
        f"<!-- {MARKER} from {src} — do not edit -->\n\n"
        f"{agent['body'].strip()}\n"
    )
    return text, warnings


def _check_effort(name, effort, model):
    """Check effort-level compatibility with the model. Return warnings."""
    if not effort:
        return []

    if effort not in FULL_RANGE:
        raise RenderError(
            f"agent '{name}': effort='{effort}' is not a Claude Code effort level "
            f"({', '.join(EFFORT_LEVELS)})"
        )

    supported = MODEL_EFFORT.get(model)
    if supported is None:
        return [
            f"agent '{name}': model '{model}' is not listed in the effort-level table — "
            f"effort='{effort}' copied unchanged; compatibility has not been checked "
            f"(VERIFY, adapters/claude.py)"
        ]

    if effort not in supported:
        raise RenderError(
            f"agent '{name}': model '{model}' does not support effort='{effort}' "
            f"(supported: {', '.join(l for l in EFFORT_LEVELS if l in supported)}).\n"
            f"    The harness would silently lower the level, and the definition would claim effort "
            f"that is not applied.\n"
            f"    Options: lower the canonical effort or choose a model "
            f"that supports this level."
        )

    return []


def _wrap(text, width=88):
    words, line, out = text.split(), "", []
    for w in words:
        if line and len(line) + 1 + len(w) > width:
            out.append(line)
            line = w
        else:
            line = f"{line} {w}".strip()
    if line:
        out.append(line)
    return out
