"""Codex adapter: canonical definitions -> .codex/agents/<name>.toml

Custom agent schema (Codex documentation, "Agent configuration / Subagents"):
required keys are `name`, `description`, and `developer_instructions`; regular
config.toml keys are also allowed. We use `model`, `model_reasoning_effort`,
and `sandbox_mode`.

Phase 5 observations implemented here (docs/harness-differences.md):

1. Access boundaries use a SANDBOX MODE that restricts the entire process.
   This can express `shell` + read-only, unlike Claude.

2. `effort` has a native field: model_reasoning_effort.

3. The prompt is stored in a TOML string and must be escaped. Escaping is the
   adapter's responsibility: canonical text is not adapted to the output format.
   Without escaping, parsing turned `\\bword\\b` into control characters
   and `C:\\temp` into a tab.

Validate output by parsing it: TOML is valid, required keys are present, and prompt
text survives serialization unchanged. Valid syntax does not guarantee a valid
schema, which is why the incorrect field name originally went unnoticed.

VERIFY: model names come from documentation and have not been tested at runtime.
If they differ, fix them HERE without changing the canonical definitions.
That is what the adapter layer is for.
"""
import re
import tomllib

from pathlib import Path

from . import RenderError

TARGET_DIR = ".codex/agents"
EXT = ".toml"

KNOWN_CAPS = {"filesystem-read", "filesystem-write", "code-search", "shell", "vcs", "web"}

# Required keys in a custom agent definition.
REQUIRED_KEYS = ("name", "description", "developer_instructions")

MARKER = "GENERATED by tools/gen_agents.py"


def render(agent, source_dir=".agents/agents"):
    caps = set(agent["capabilities"])
    warnings = []

    sandbox = "workspace-write" if "filesystem-write" in caps else "read-only"

    if "web" in caps:
        warnings.append(
            f"agent '{agent['name']}': capability 'web' is not mapped to Codex configuration — "
            f"network access is configured separately from sandbox_mode (VERIFY)"
        )

    body = agent["body"].strip()
    desc = agent["description"].strip()
    src = f"{Path(source_dir).as_posix()}/{agent['name']}.md"

    text = (
        f"# {MARKER} from {src} — do not edit\n\n"
        f'name = "{_esc(agent["name"])}"\n'
        f'description = """\n{_ml(_fill(desc))}\n"""\n\n'
        f'model = "{_esc(agent["models"]["codex"])}"\n'
        f'model_reasoning_effort = "{_esc(agent["effort"])}"\n\n'
        f"# capabilities: {', '.join(sorted(caps))}\n"
        f'sandbox_mode = "{sandbox}"\n\n'
        f'developer_instructions = """\n{_ml(body)}\n"""\n'
    )

    _check(text, agent["name"], desc, body)
    return text, warnings


def _check(text, name, desc, body):
    """Parse output and validate its schema. A failure here is an adapter bug."""
    try:
        data = tomllib.loads(text)
    except tomllib.TOMLDecodeError as e:
        raise RenderError(f"agent '{name}': generated invalid TOML: {e}") from e

    missing = [k for k in REQUIRED_KEYS if not str(data.get(k, "")).strip()]
    if missing:
        raise RenderError(
            f"agent '{name}': output is missing required custom agent keys: "
            f"{', '.join(missing)}"
        )

    if data["developer_instructions"].strip() != body:
        raise RenderError(
            f"agent '{name}': prompt text changed during TOML serialization — "
            f"adapter escaping error"
        )

    if data["description"].split() != desc.split():
        raise RenderError(
            f"agent '{name}': description text changed during TOML serialization — "
            f"adapter escaping error"
        )


def _esc(s):
    """Value of a single-line basic TOML string."""
    return _ctrl(s.replace("\\", "\\\\").replace('"', '\\"'))


def _ml(s):
    r"""Body of a multiline basic TOML string \"\"\"...\"\"\".

    Backslashes start escape sequences inside this string, so always escape them.
    Escape quotes only where they would merge with the delimiter: runs of three
    or more quotes and quotes at the end of the string.
    """
    s = s.replace("\\", "\\\\")
    s = re.sub(r'"{3,}', lambda m: '\\"' * len(m.group(0)), s)
    s = re.sub(r'"+\Z', lambda m: '\\"' * len(m.group(0)), s)
    return _ctrl(s, keep="\n\t")


def _ctrl(s, keep=""):
    """Control characters must be escaped in a TOML string."""
    return "".join(
        ch if ch in keep or (0x20 <= ord(ch) and ord(ch) != 0x7F) else "\\u%04X" % ord(ch)
        for ch in s
    )


def _fill(text, width=88):
    words, line, out = text.split(), "", []
    for w in words:
        if line and len(line) + 1 + len(w) > width:
            out.append(line)
            line = w
        else:
            line = f"{line} {w}".strip()
    if line:
        out.append(line)
    return "\n".join(out)
