"""Адаптер Codex: канон -> .codex/agents/<name>.toml

Схема custom agent (документация Codex, «Agent configuration / Subagents»):
обязательные ключи — `name`, `description`, `developer_instructions`; сверх них
допустимы обычные ключи config.toml, из которых мы используем `model`,
`model_reasoning_effort` и `sandbox_mode`.

Наблюдения этапа 5, реализованные здесь (docs/harness-differences.md):

1. Границы задаются РЕЖИМОМ ПЕСОЧНИЦЫ, ограничивающим процесс целиком. Поэтому
   `shell` + read-only здесь выразимо — в отличие от Claude.

2. `effort` имеет носитель: model_reasoning_effort.

3. Промпт кладётся в TOML-строку, поэтому его нужно экранировать. Экранирование —
   ответственность адаптера: канонический текст не подгоняется под формат вывода.
   Без экранирования `\\bword\\b` после разбора превращался в управляющие символы,
   а `C:\\temp` — в табуляцию.

Выход проверяется разбором: TOML валиден, обязательные ключи на месте, текст промпта
пережил сериализацию без изменений. Синтаксическая валидность схему не гарантирует —
именно поэтому неправильное имя поля жило здесь незамеченным.

VERIFY: имена моделей написаны по документации и не проверялись запуском. Если они
окажутся другими — правится ЗДЕСЬ, канона это не касается. Ради этого адаптерный
слой и существует.
"""
import re
import tomllib

from pathlib import Path

from . import RenderError

TARGET_DIR = ".codex/agents"
EXT = ".toml"

KNOWN_CAPS = {"filesystem-read", "filesystem-write", "code-search", "shell", "vcs", "web"}

# Обязательные ключи определения custom agent.
REQUIRED_KEYS = ("name", "description", "developer_instructions")

MARKER = "GENERATED by tools/gen_agents.py"


def render(agent, source_dir=".agents/agents"):
    caps = set(agent["capabilities"])
    warnings = []

    sandbox = "workspace-write" if "filesystem-write" in caps else "read-only"

    if "web" in caps:
        warnings.append(
            f"агент '{agent['name']}': capability 'web' не отображена в конфиг Codex — "
            f"сетевой доступ настраивается отдельно от sandbox_mode (VERIFY)"
        )

    body = agent["body"].strip()
    desc = agent["description"].strip()
    src = f"{Path(source_dir).as_posix()}/{agent['name']}.md"

    text = (
        f"# {MARKER} from {src} — do not edit\n\n"
        f'name = "{_esc(agent["name"])}"\n'
        f'description = """\n{_ml(_fill(desc))}\n"""\n\n'
        f'model = "{_esc(agent["models"]["codex"])}"\n'
        f'model_reasoning_effort = "{_esc(agent["effort"])}"\n\n'
        f"# capabilities: {', '.join(sorted(caps))}\n"
        f'sandbox_mode = "{sandbox}"\n\n'
        f'developer_instructions = """\n{_ml(body)}\n"""\n'
    )

    _check(text, agent["name"], desc, body)
    return text, warnings


def _check(text, name, desc, body):
    """Разбирает вывод и сверяет со схемой. Ошибка здесь — баг адаптера."""
    try:
        data = tomllib.loads(text)
    except tomllib.TOMLDecodeError as e:
        raise RenderError(f"агент '{name}': сгенерирован невалидный TOML: {e}") from e

    missing = [k for k in REQUIRED_KEYS if not str(data.get(k, "")).strip()]
    if missing:
        raise RenderError(
            f"агент '{name}': в выводе нет обязательных ключей custom agent: "
            f"{', '.join(missing)}"
        )

    if data["developer_instructions"].strip() != body:
        raise RenderError(
            f"агент '{name}': текст промпта изменился при сериализации в TOML — "
            f"ошибка экранирования в адаптере"
        )

    if data["description"].split() != desc.split():
        raise RenderError(
            f"агент '{name}': текст description изменился при сериализации в TOML — "
            f"ошибка экранирования в адаптере"
        )


def _esc(s):
    """Значение однострочной базовой TOML-строки."""
    return _ctrl(s.replace("\\", "\\\\").replace('"', '\\"'))


def _ml(s):
    r"""Тело многострочной базовой TOML-строки \"\"\"...\"\"\".

    Внутри такой строки обратный слэш начинает escape-последовательность, поэтому
    он экранируется всегда. Кавычки экранируются только там, где сливаются
    с разделителем: серия из трёх и больше и хвост строки.
    """
    s = s.replace("\\", "\\\\")
    s = re.sub(r'"{3,}', lambda m: '\\"' * len(m.group(0)), s)
    s = re.sub(r'"+\Z', lambda m: '\\"' * len(m.group(0)), s)
    return _ctrl(s, keep="\n\t")


def _ctrl(s, keep=""):
    """Управляющие символы в TOML-строке недопустимы без экранирования."""
    return "".join(
        ch if ch in keep or (0x20 <= ord(ch) and ord(ch) != 0x7F) else "\\u%04X" % ord(ch)
        for ch in s
    )


def _fill(text, width=88):
    words, line, out = text.split(), "", []
    for w in words:
        if line and len(line) + 1 + len(w) > width:
            out.append(line)
            line = w
        else:
            line = f"{line} {w}".strip()
    if line:
        out.append(line)
    return "\n".join(out)
